#!/usr/bin/env bash

set -euo pipefail

function main(){
  local path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  local init_file="${path}/init-file"
  export PROJECT_DIR=$(cd "$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}" )" )" )" && pwd)
  type gnome-terminal >/dev/null 2>&1 \
    && gnome-terminal -- bash --init-file $init_file \
    || bash --init-file $init_file
}
main "$@"

#unset -f main