#!/usr/bin/env bash

function _project_prepend_path(){
  local path=$1
  if [[ -d "$path" ]]; then
    if [[ ":$PATH:" != *":$path:"* ]]; then
      export PATH=$path:$PATH
    fi
  fi
}

function _main(){
  export PROJECT_PATH=${PROJECT_PATH-"$(pwd)"}

  if [ -f "$HOME/.bash_profile" ]; then
    . "$HOME/.bash_profile"
  elif [ -f "$HOME/.profile" ]; then
    . "$HOME/.profile"
  fi

  # project paths
  # the priority follow the logic:
  #  1. project bin (lower)
  #  2. user
  #  3. extra paths
  #  4. project Local/bin (higher)

  _project_prepend_path $PROJECT_PATH/b-lib/bin
  _project_prepend_path $PROJECT_PATH/bin
  _project_prepend_path $PROJECT_PATH/local/bin

  if [ "$(type -t __git_ps1)" == "function" ]; then
    export PS1=${PROJECT_PROMPT:-'\n\[\033[92m\]\u@\h \[\033[91m\]$PROJECT_TITLE \[\033[93m\]\w\[\033[95m\]$(__git_ps1 " (%s)")\[\033[0m\]\n\$ '}
    export GIT_PS1_SHOWDIRTYSTATE=1
  else
    export PS1=${PROJECT_PROMPT:-"\n\[\033[92m\]\u@\h \[\033[91m\]$PROJECT_TITLE \[\033[93m\]\w\[\033[0m\]\n\$ "}
  fi

  if [[ -d "$PROJECT_PATH/local" ]]; then
    export HISTFILE=$PROJECT_PATH/local/.bash_history
  fi

  cd $PROJECT_PATH

  hash -r

}

_main "$@"

unset -f _project_prepend_path
unset -f _main
