#!/usr/bin/env bash

set -euo pipefail

function main(){
  local path="$( cd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )" && pwd )"
  local start="$path/project"
  test -f "$start" && return 1

  local bin="$path/bin"
  local local="$path/local/bin"
  local start_cmd="$path/project.cmd"
  local project_title=${1:-BeeLib Project}


  mkdir --parents "$bin" "$local"
  echo * > "$local/.gitignore"
  local project_path='$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)'
  local start_bin='$(dirname "$(realpath "${BASH_SOURCE[0]}")")/beelib/project-start start'

  cat << EOF > $start
#!/usr/bin/env bash
PROJECT_TITLE="$project_title" \\
PROJECT_PATH=$project_path \\
$start_bin
EOF
  chmod +x $start

}

main "$@"

unset -f main